export const CURRENCY_CODES = {
  EUR: 'EUR',
  GBP: 'GBP',
  USD: 'USD',
};

export const CURRENY_OPTIONS = {
  MINIMUM_TWO_MAXIMUM_FOUR_DECIMAL_PLACES: {
    MINIMUM_DIGITS: 2,
    MAXIMUM_DIGITS: 4,
  },
};
